---
- name: Install metric beat
  hosts: webservers
  become: true
  tasks:

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: install metricbeat deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: drop in metricbeat.yml
    copy:
      src: /etc/ansible/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure system module for metricbeat
    command: metricbeat modules enable docker

  - name: setup metric beat
    command: metricbeat setup

  - name: Start metricbeat
    command: service metricbeat start

  - name: enable metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes
